# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.caching=true

# Mod properties
mod.version=1.3.3
mod.group=circuitlord.reactivemusic
mod.id=reactivemusic
mod.name=Reactive Music

# Used for mod metadata
mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]
mod.loader_dep_forge=[VERSIONED]
mod.loader_dep_neoforge=[VERSIONED]

# Mod setup
deps.fabric_loader=0.16.14
deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.neoforge_patch=[VERSIONED]

# Mod dependencies
deps.yarn_build=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.modmenu=[VERSIONED]
